name: pbpm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - jellyfish=0.7.2
  - h5py=2.10.0
  - matplotlib=3.2.1
  - numpy=1.18.1
  - tensorflow=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.0
  - pip=20.0.2
  - pip:
    - pandas==1.0.3
    - scikit-learn==0.22.2
    - distance==0.1.3
    - optuna==3.2.0
    - optuna-dashboard==0.12.0
